services:
  - type: web
    name: agent-factory
    runtime: docker
    repo: https://github.com/wolzey/agent-factory
    branch: main
    autoDeploy: true
    plan: free
    envVars:
      - key: AF_TOKEN_SECRET
        generateValue: true
      - key: HOST
        value: 0.0.0.0
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: TITLE
        value: AGENT FACTORY
      - key: ENVIRONMENT
        value: factory25d
